src/Entity/Employment.php
<?php

namespace App\Entity;

use App\Repository\EmploymentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EmploymentRepository::class)
 */
class Employment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="date")
     */
    private $added_on;

    public function __construct()
    {
        $datetime = new \DateTime('now');
        $this->added_on = $datetime;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAddedOn(): ?\DateTimeInterface
    {
        return $this->added_on;
    }

    public function setAddedOn(\DateTimeInterface $added_on): self
    {
        $this->added_on = $added_on;

        return $this;
    }
}

src/Form/EmploymentType.php
<?php

namespace App\Form;

use App\Entity\Employment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmploymentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class)
            ->add('content', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Employment::class,
        ]);
    }
}

src/Controller/EmploymentController.php
<?php

namespace App\Controller;

use App\Entity\Employment;
use App\Form\EmploymentType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EmploymentController extends AbstractController
{
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/employment", name="employment")
     */
    public function home()
    {
       $employment=$this->getDoctrine()->getRepository(Employment::class)->findAll();
       return $this->render('employment/index.html.twig', ['employment'=>$employment]);
    }



   /**
     * @IsGranted("ROLE_USER")
     * @Route ("/employment/{id}", name="employment_view")
     * @param $id
     * @return Response
     */
    public function viewSingle($id){
        $employment=$this->getDoctrine()->getRepository(Employment::class)->find($id);
        return $this->render('employment/employment_view.html.twig', ['employment'=>$employment]);
    }

    /**
     * @Route ("/create", name="create")
     * @param Request $request
     * @return Response
     */
    public function create(Request $request):Response {

        $employment=new Employment();
        $form=$this->createForm(EmploymentType::class,$employment);
        $form->handleRequest($request);

        if($form->isSubmitted()&&$form->isValid()){
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($employment);
            $entityManager->flush();
            return $this->redirectToRoute('employment');
        }
        return $this->render('employment/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route ("/employment/edit/{id}", name="employment_edit")
     * @param $id
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function edit($id, Request $request){
     $employment=$this->getDoctrine()->getRepository(Employment::class)->find($id);
     if($employment===null){
         return $this->redirectToRoute('');
     }
     $form=$this->createForm(EmploymentType::class, $employment);
     $form->handleRequest($request);

     if($form->isValid()&& $form->isSubmitted()){
         $entityManager= $this->getDoctrine()->getManager();
         $entityManager->persist($employment);
         $entityManager->flush();
         $this->redirectToRoute('');
     }
     return $this->render('');
    }

    /**
     *  @Route ("/employment/delete/{id}", name="employment_delete")
     * @param $id
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function delete($id, Request $request){
        $employment=$this->getDoctrine()->getRepository(Employment::class)->find($id);
        if($employment===null){
            return $this->redirectToRoute('');
        }
        $form=$this->createForm(EmploymentType::class, $employment);
        $form->handleRequest($request);

        if($form->isValid()&& $form->isSubmitted()){
            $entityManager= $this->getDoctrine()->getManager();
            $entityManager->remove($employment);
            $entityManager->flush();
            $this->redirectToRoute('');
        }
        return $this->render('');
    }
}

templates/employment/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create employment!{% endblock %}

{% block body %}
    {{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.content) }}
    <a class="btn btn-default" href="{{ path('employment') }}">Cancel</a>
    <button type="submit" class="btn btn-primary">Create</button>
    {{ form_end(form) }}
{% endblock %}

templates/employment/employment_view.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container body-content">
        <div class="row">
            <div class="col-md-12">
                <article>
                    <header>
                        <h2>{{ employment.title }}</h2>
                    </header>

                    <p>
                        {{ employment.content }}
                    </p>

                    <small class="author">
                        {{ employment.addedOn|date('d.m.Y') }}
                    </small>

                    <footer>
                        <div class="pull-right">
                            <a class="btn btn-default btn-xs" href="{{ path('employment') }}">back &raquo;</a>
                            <a class="btn btn-default btn-xs" href="#">Apply</a>
                        </div>
                    </footer>
                </article>
            </div>
        </div>
    </div>

{% endblock %}

templates/employment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
<div class="container body-content">
    <div class="row">
        {% for employment in employment %}
        <div class="col-md-6">
            <article>
                <header>
                    <h2>{{ employment.title }}</h2>
                </header>

                <p>
                    {{ employment.content }}
                </p>

                <small class="author">
                  {# {{ employment.addedOn }}#}
                </small>
             <div class="pull-right">
                    <a class="btn btn-default btn-xs"
                       href="{{ path('employment_view', {'id':employment.id}) }}">Read more &raquo;</a>
                </div>
            </article>
        </div>
    </div>
            </div>
{% endfor %}
{% endblock %}